import React from 'react';
import { Link } from 'react-router-dom';
import { FiArrowUpRight, FiCheck, FiLayers, FiShield, FiDroplet, FiTool } from 'react-icons/fi';

const lines = [
  { icon: <FiLayers />, title: 'Jotafloor® epoxy systems', text: 'Seamless floor systems for industrial and commercial concrete, selected around traffic, cleaning, exposure and the condition of the base.', link: '/services/epoxy-flooring', image: '/images/service-references/industrial-floor-reference.webp', tag: 'EPOXY / FLOOR' },
  { icon: <FiDroplet />, title: 'Polyurethane coatings', text: 'PU floor finishes and resilient systems for selected environments where flexibility, wear and cleanability matter.', link: '/services/polyurethane-floor', image: '/images/services/gray-matte.jpg', tag: 'PU / RESIN' },
  { icon: <FiShield />, title: 'Protective industrial paints', text: 'Protective coatings for steel, concrete and plant assets, matched to preparation, exposure and a practical maintenance plan.', link: '/services/industrial-paint-coatings', image: '/images/services/roller-closeup.jpg', tag: 'STEEL / CONCRETE' },
  { icon: <FiTool />, title: 'Waterproof coating systems', text: 'Roof, terrace and basement waterproofing with details, joints, falls and terminations planned as part of the complete system.', link: '/services/waterproofing-coatings', image: '/images/roof-waterproofing.webp', tag: 'ROOF / TERRACE' }
];

export default function PaintsPage() {
  return (
    <main className="inner-page paints-page">
      <section className="page-hero page-hero--paints"><div className="container page-hero__grid"><div className="page-hero__copy"><div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><span>Paints & coatings</span></div><p className="eyebrow">PREMIUM PAINTS · PROTECTIVE COATINGS</p><h1>Protection,<br /><em>in every layer.</em></h1><p>Explore high-quality coating systems for floors, steel, concrete and water-exposed structures. Multilines Coating Solutions pairs materials with site-led preparation and application planning.</p><div className="page-hero__actions"><Link to="/products" className="button button--accent">Browse products <FiArrowUpRight /></Link><Link to="/contact" className="location-chip">Talk to a coatings specialist <FiArrowUpRight /></Link></div></div><div className="paints-hero-art"><img src="/images/services/worker-roller.jpg" alt="Applying a seamless protective floor coating" /><div className="paints-hero-art__shade" /><span className="paints-hero-art__caption">MATERIAL / PREPARATION / PERFORMANCE</span></div></div></section>

      <section className="section paints-intro" data-reveal><div className="container paints-intro__grid"><div className="section-index"><span>01</span><i /> COATING WITH INTENT</div><div><h2>A better finish begins<br /><em>with the right system.</em></h2><p className="lead-paragraph">Premium coatings are more than a top layer. The substrate, surface preparation, primer, build coat, finish and detailing all contribute to the final result.</p><p>Our team helps select a suitable coating family and coordinate its application around the operating environment. Exact products, colour, coverage and performance are confirmed from the project brief and manufacturer technical information.</p><div className="paints-intro__checklist"><span><FiCheck /> Jotafloor® epoxy and PU flooring</span><span><FiCheck /> Protective paints for steel and concrete</span><span><FiCheck /> Waterproofing for roofs, terraces and basements</span></div></div><figure className="paints-intro__photo"><img src="/images/roof-waterproofing.webp" alt="Illustrative reference of a protective waterproof coating application" loading="lazy" /><figcaption>PREPARATION / PROTECTION / FINISH</figcaption></figure></div></section>

      <section className="section paints-lines" data-reveal><div className="container"><div className="section-heading-row"><div><div className="section-index"><span>02</span><i /> SYSTEM FAMILIES</div><h2>Choose by exposure.<br /><em>Apply with precision.</em></h2></div><p>Each coating family responds to different surface, use and environmental conditions. Explore the scope, then request a recommendation for your site.</p></div><div className="paints-lines-grid">{lines.map((line, index) => <article className="paint-line-card" key={line.title}><div className="paint-line-card__image"><img src={line.image} alt={`${line.title} illustrative reference`} loading="lazy" /><span>{line.tag}</span><i>0{index + 1}</i></div><div className="paint-line-card__body"><div className="paint-line-card__icon">{line.icon}</div><h3>{line.title}</h3><p>{line.text}</p><Link to={line.link} className="text-link text-link--dark">Explore this system <FiArrowUpRight /></Link></div></article>)}</div></div></section>

      <section className="section paints-callout" data-reveal><div className="container paints-callout__inner"><div><span className="section-index section-index--light"><span>03</span><i /> SPECIFICATION & SUPPLY</span><h2>Share the site details.<br /><em>We’ll help shape the scope.</em></h2></div><div><p>Send the location, area, substrate, current surface condition and how the space is used. We can discuss suitable materials, preparation, programme and supply options with you.</p><div className="paints-callout__actions"><Link to="/contact" className="button button--light">Request a coating consultation <FiArrowUpRight /></Link><Link to="/products" className="text-link">Visit product store <FiArrowUpRight /></Link></div></div></div></section>
    </main>
  );
}
