import React from 'react';
import { Link } from 'react-router-dom';
import { FiArrowUpRight, FiCheck, FiLayers, FiShield, FiDroplet, FiActivity, FiTool, FiTarget } from 'react-icons/fi';

const systems = [
  { n: '01', title: 'Epoxy resin', type: 'Industrial & commercial', text: 'Seamless epoxy systems for environments where cleanability, abrasion, traffic or chemical resistance need to be considered.', icon: <FiLayers />, detail: 'Jotafloor® epoxy systems', url: '/services/epoxy-flooring', image: '/images/services/warehouse-application.jpg' },
  { n: '02', title: 'Polyurethane', type: 'Flexible & resilient', text: 'PU finishes for selected floor environments, and resilient sports systems designed for indoor activity.', icon: <FiActivity />, detail: 'PU floor & sports systems', url: '/services/polyurethane-floor', image: '/images/services/gray-matte.jpg' },
  { n: '03', title: 'Acrylic sports surfacing', type: 'Courts & recreation', text: 'Textured, coloured court coatings for suitable outdoor bases, with options for selected cushioned build-ups.', icon: <FiTarget />, detail: 'Acrylic court systems', url: '/services/acrylic-sports-flooring', image: '/images/service-references/acrylic-sports-flooring.webp' },
  { n: '04', title: 'SBR & EPDM rubber', type: 'Tracks & activity areas', text: 'Resilient rubber surface families for running tracks, play areas, gyms and selected impact attenuation applications.', icon: <FiShield />, detail: 'Rubber sports systems', url: '/services/epdm-running-tracks', image: '/images/service-references/epdm-running-tracks.webp' },
  { n: '05', title: 'Protective paint coatings', type: 'Steel, concrete & plant', text: 'Coating systems for industrial assets exposed to corrosion, weather, wear or specific operating conditions.', icon: <FiDroplet />, detail: 'Industrial paint & coatings', url: '/services/industrial-paint-coatings', image: '/images/services/roller-closeup.jpg' },
  { n: '06', title: 'Concrete repair', type: 'Repair & preparation', text: 'Repair mortars and surface treatments to reinstate damaged concrete and prepare the base for a new finish.', icon: <FiTool />, detail: 'Concrete repair & maintenance', url: '/services/concrete-repair-maintenance', image: '/images/services/concrete-prep.png' }
];

export default function SystemsPage() {
  return (
    <main className="inner-page systems-page">
      <section className="page-hero page-hero--systems"><div className="container page-hero__grid"><div className="page-hero__copy"><div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><span>Systems</span></div><p className="eyebrow">MATERIALS · PERFORMANCE · APPLICATION</p><h1>Materials matter.<br /><em>So does the method.</em></h1><p>We bring coating products and installation expertise together. The system is selected for the substrate, service conditions and finished surface—not by product name alone.</p><div className="page-hero__actions"><Link to="/contact" className="button button--accent">Talk through a system <FiArrowUpRight /></Link><span className="location-chip">Jotun · Jotafloor® systems</span></div></div><div className="systems-hero-photo"><img src="/images/service-references/industrial-floor-reference.webp" alt="Illustrative reference of a seamless resin floor" loading="lazy" /><span>SYSTEM / LAYER / FINISH</span></div></div></section>

      <section className="section systems-intro" data-reveal><div className="container systems-intro__grid"><div className="section-index"><span>01</span><i /> HOW WE SPECIFY</div><div><h2>Look beneath the finish.<br /><em>Get the system right.</em></h2><p className="lead-paragraph">A coating performs as a complete build-up. The slab, repair detail, primer, body coat and top layer all play a part.</p><p>We help clients identify the right system family, work through the practical site conditions and align the installation with manufacturer data and project requirements. Exact products, thicknesses and cure windows are agreed for the project.</p></div><figure className="systems-intro__photo"><img src="/images/service-references/epdm-running-tracks.webp" alt="Illustrative EPDM track finish showing resilient sports surfacing" loading="lazy" /><figcaption>SPORTS / INDUSTRIAL / PROTECTIVE SYSTEMS</figcaption></figure></div></section>

      <section className="section systems-grid-section" data-reveal><div className="container"><div className="section-heading-row"><div><div className="section-index"><span>02</span><i /> SYSTEM FAMILIES</div><h2>One brief.<br /><em>Many possibilities.</em></h2></div><p>Explore the coating and surfacing families we work with. Each project is assessed individually before a specification is finalised.</p></div><div className="systems-grid">{systems.map((system) => <article className="system-card" key={system.n}><div className="system-card__image"><img src={system.image} alt="" loading="lazy" /><span>{system.n}</span></div><div className="system-card__body"><span className="system-card__type">{system.type}</span><h3>{system.title}</h3><p>{system.text}</p><div className="system-card__detail">{system.icon}<span>{system.detail}</span></div><Link to={system.url} className="text-link text-link--dark">Explore system <FiArrowUpRight /></Link></div></article>)}</div></div></section>

      <section className="section system-note" data-reveal><div className="container system-note__grid"><div><span className="system-note__badge"><FiCheck /> PROJECT-LED SELECTION</span><h2>Product data meets<br /><em>real site conditions.</em></h2></div><div><p>All coating recommendations should be checked against the relevant manufacturer technical data, substrate condition and environmental conditions at the time of application.</p><Link to="/contact" className="button button--dark">Request a project review <FiArrowUpRight /></Link></div></div></section>
    </main>
  );
}
